[tools]
act = "0.2.83"
aichat = "0.30.0"
"aqua:JanDeDobbeleer/oh-my-posh" = "28.2.0"
"aqua:ivaaaan/smug" = "0.3.12"
atuin = "18.10.0"
awscli = "2.32.14"
azure-cli = "2.81.0"
azure-kubelogin = "0.2.13"
bat = "0.26.1"
bat-extras = "2024.08.24"
bitwarden = "2025.12.0"
btop = "1.4.5"
chezmoi = "2.68.1"
cidrchk = "0.5"
claude-code = "2.0.67"
coder = "2.29.1"
direnv = "2.37.1"
doggo = "1.1.2"
duf = "0.9.1"
dust = "1.2.3"
eza = "0.23.4"
fastfetch = "2.56.0"
fd = "10.3.0"
flux2 = "2.7.5"
fzf = "0.67.0"
gcloud = "549.0.1"
github-cli = "2.83.2"
golangci-lint = "2.7.2"
goreleaser = "2.13.1"
gum = "0.17.0"
hadolint = "2.14.0"
helm = "4.0.2"
helm-diff = "3.14.1"
just = "1.45.0"
k9s = "0.50.16"
kubecolor = "0.5.3"
kubectl = "1.33.5"
lazydocker = "0.24.2"
lazygit = "0.57.0"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
opencode = "1.0.91"
opentofu = "1.11.1"
prettier = "3.7.4"
ripgrep = "15.1.0"
ripgrep-all = "0.10.10"
ripsecrets = "0.1.11"
semver = "3.4.0"
shellcheck = "0.11.0"
sops = "3.11.0"
stern = "1.33.1"
terraform = "1.14.2"
terraform-docs = "0.20.0"
terraform-ls = "0.38.3"
terraform-validator = "3.1.3"
tf-summarize = "0.3.14"
tflint = "0.60.0"
tmux = "3.6a"
usage = "2.9.0"
usql = "0.19.26"
watchexec = "2.3.2"
zoxide = "0.9.8"


[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[env]
IS_MONTBLU_DEVOPS = "yes"
