[tools]
act = "latest"
aichat = "latest"
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
"aqua:ivaaaan/smug" = "latest"
atuin = "latest"
awscli = "2.31.18"
azure-cli = "2.78.0"
azure-kubelogin = "latest"
bat = "latest"
bat-extras = "latest"
bitwarden = "latest"
btop = "latest"
chezmoi = "latest"
cidrchk = "latest"
claude-code = "latest"
coder = "latest"
direnv = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
gcloud = "543.0.0"
github-cli = "latest"
golangci-lint = "latest"
goreleaser = "latest"
gum = "latest"
hadolint = "latest"
helm = "3.19.0"
helm-diff = "latest"
just = "latest"
k9s = "latest"
kubecolor = "latest"
kubectl = "1.33.5"
lazydocker = "latest"
lazygit = "latest"
node = "22"
"npm:@angular/cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
opencode = "latest"
opentofu = "latest"
prettier = "latest"
ripgrep-all = "latest"
semver = "latest"
shellcheck = "latest"
sops = "latest"
stern = "latest"
terraform = "1.5.2"
terraform-docs = "latest"
terraform-ls = "latest"
terraform-validator = "latest"
tf-summarize = "latest"
tflint = "latest"
tmux = "latest"
usage = "latest"
usql = "latest"
watchexec = "latest"
zoxide = "latest"


[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[env]
IS_MONTBLU_DEVOPS = "yes"
